INSERT INTO CART.TB_CATEGORIA_CATALOG (ID, NAME) VALUES(2, 'CAT_ROOT');
INSERT INTO CART.TB_CATEGORIA_CATALOG (ID, NAME, PARENT_CATEGORY) VALUES(3, 'CAT A', 2);
INSERT INTO CART.TB_CATEGORIA_CATALOG (ID, NAME, PARENT_CATEGORY) VALUES(4, 'CAT B', 2);
INSERT INTO CART.TB_CATEGORIA_CATALOG (ID, NAME, PARENT_CATEGORY) VALUES(5, 'CAT C', 3);
INSERT INTO CART.TB_CATEGORIA_CATALOG (ID, NAME, PARENT_CATEGORY) VALUES(6, 'CAT D', 5);